phone: "1-989-486-1924"
email: "hello@wearetreepeople.com"
address: "1543 East Ednor Court, Midland, MI"
service_area: ""
facebook_url: "https://www.facebook.com/advancedarborist/"
instagram_url: "https://www.instagram.com/advancedarborist/"
